#集合
A={"a","b","c"}
B=set("aabbcce")
print(A-B)
print(A&B)
print(A^B)#不同时包含
print(A|B)#并集
#集合的增添
A.add("n")
B.update({1,3},[2,4],{"e"})
#删除元素
A.remove("a")#如果没有的话会报错
A.discard("f")#如果没有的话不会报错
A.pop()#随机删除
#字典
dic={'name':'张三','age':19,'school':'sctu'}
#修改数据
dic['name']='李四'
print(dic)
#查找数据
dic.get('name')
dic.setdefault('name')
#增加数据
dic['class']='一班'
print(dic)
#删除数据
del dic['name']
dic.pop('name')
dic.popitem('class')
print(dic)
print