#爬虫，学习了requests库，正则表达式以及bs4
#输入：
name=input()
print(3,name,sep=',')
print(3,name,end=',')
print(3,name);print(3,name)

#find函数：
print('abcdef'.find('cd'))
print('abcd'.find('ak'))
#join函数：
print((',').join('abc'))
#split函数：
print('a,b,c'.split(','))
#进制转换：
print(int('2a',base=16))
print(0x2a)
#转换成utf-8编码或者gbk编码
wd='我爱python！'
print(wd.encode('utf-8'))
print(wd.encode('gbk'))
print(b'\xe6\x88\x91\xe7\x88\xb1python\xef\xbc\x81'.decode('utf-8'))
#用is进行验证：
a=2
b=2
print(a is b)
#列表可以进行+、*
print([1,2]+[3,4])
print([1,]*4)
#dict:
s={'a':1,'b':2}
print(s.get('a'))
print(s.get('f'))
print(s.get('f',3))
print(s.get('a',4))
s.update({'c':6,'a':7})
print(s)
print(s.setdefault('b'))
s['d']=8
print(s)